# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class HousePriceItem(scrapy.Item):
    # define the fields for your item here like:

    city = scrapy.Field()

    bedrooms = scrapy.Field()
    bathrooms = scrapy.Field()
    propertyType = scrapy.Field()
    balconies = scrapy.Field()
    postedOn = scrapy.Field()
    furnishing = scrapy.Field()
    facing = scrapy.Field()
    flrNum = scrapy.Field()
    totalFlrNum = scrapy.Field()
    RentOrSale = scrapy.Field()
    locality = scrapy.Field()
    carpetArea = scrapy.Field()
    carpetAreaUnit = scrapy.Field()
    URLs = scrapy.Field()
    Lat = scrapy.Field()
    Long = scrapy.Field()
    noOfLifts = scrapy.Field()
    securityDeposit = scrapy.Field()
    maintenanceCharges = scrapy.Field()
    maintenanceChargesFrequency = scrapy.Field()
    firstMonthCharges = scrapy.Field()
    brokerage = scrapy.Field()
    exactPrice = scrapy.Field()
    sqftPrice = scrapy.Field()

    Piped_Gas = scrapy.Field()
    Early_Learning_Centre = scrapy.Field()
    Golf_Course = scrapy.Field()
    Intercom_Facility = scrapy.Field()
    Waste_Disposal = scrapy.Field()
    Indoor_Squash__And__Badminton_Courts = scrapy.Field()
    Water_Storage = scrapy.Field()
    Outdoor_Tennis_Courts = scrapy.Field()
    Kids_Club = scrapy.Field()
    Cricket_net_practice = scrapy.Field()
    Health_club_with_Steam__Or__Jaccuzi = scrapy.Field()
    RO_Water_System = scrapy.Field()
    Gymnasium = scrapy.Field()
    Recreational_Pool = scrapy.Field()
    Skydeck = scrapy.Field()
    Flower_Gardens = scrapy.Field()
    Kids_Play_Pool_With_Water_Slides = scrapy.Field()
    Jogging_and_Strolling_Track = scrapy.Field()
    Air_Conditioned = scrapy.Field()
    Fire_Fighting_Equipment = scrapy.Field()
    Private_Terrace_Or_Garden = scrapy.Field()
    Security = scrapy.Field()
    Mini_Cinema_Theatre = scrapy.Field()
    Conference_Room = scrapy.Field()
    Cafeteria_Or_Food_Court = scrapy.Field()
    Private_Garden = scrapy.Field()
    Vaastu_Compliant = scrapy.Field()
    Retail_Boulevard___Retail_Shops__ = scrapy.Field()
    Bank__And__ATM = scrapy.Field()
    Earth_quake_resistant = scrapy.Field()
    Club_House = scrapy.Field()
    Lift = scrapy.Field()
    AEROBICS_ROOM = scrapy.Field()
    Guest_Accommodation = scrapy.Field()
    Activity_Deck4 = scrapy.Field()
    DTH_Television_Facility = scrapy.Field()
    Visitor_Parking = scrapy.Field()
    Concierge_Services = scrapy.Field()
    Park = scrapy.Field()
    Banquet_Hall = scrapy.Field()
    Laundry_Service = scrapy.Field()
    Canopy_Walk = scrapy.Field()
    Internet_Or_Wi_Fi_Connectivity = scrapy.Field()
    Grand_Entrance_lobby = scrapy.Field()
    Dance_Studio = scrapy.Field()
    Service_Or_Goods_Lift = scrapy.Field()
    Multipurpose_Courts = scrapy.Field()
    Reserved_Parking = scrapy.Field()
    Rentable_Community_Space = scrapy.Field()
    Rain_Water_Harvesting = scrapy.Field()
    CCTV_Camera = scrapy.Field()
    Bar_Or_Lounge = scrapy.Field()
    Indoor_Games_Room = scrapy.Field()
    Multipurpose_Hall = scrapy.Field()
    Arts__And__Craft_Studio = scrapy.Field()
    Coffee_Lounge__And__Restaurants = scrapy.Field()
    Swimming_Pool = scrapy.Field()
    Meditation_Area = scrapy.Field()
    Library_And_Business_Centre = scrapy.Field()
    Barbeque_Pit = scrapy.Field()
    Event_Space__And__Amphitheatre = scrapy.Field()
    Library = scrapy.Field()
    Maintenance_Staff = scrapy.Field()
    Cycling__And__Jogging_Track = scrapy.Field()
    Kids_Play_Area = scrapy.Field()
    Power_Back_Up = scrapy.Field()
