from typing import List
from setuptools import setup, find_packages

# Define a flag and project name
flag = '-e .'
project_name = 'LLM_Text_Detector'

# Function to read required packages from a file
def required_packages(filepath: str) -> List[str]:
    requirements = []

    # Open the specified file and read lines
    with open(filepath, 'r') as f:
        requirements = f.readlines()

        # Remove newline characters from each requirement
        requirements = [requirement.replace('\n', '') for requirement in requirements]

    # If the flag is present, remove it from the list of requirements
    if flag in requirements:
        requirements.remove(flag)

    return requirements

# Setup function to configure package information
setup(
    name=project_name,
    version='0.0.1',
    author='Deepak Saini',
    author_email='deepak170602@gmail.com',
    description="Classifies text generated by LLMs",
    packages=find_packages(),
    # Specify required packages by calling the function with the requirements file
    install_requires=required_packages('requirements.txt')
)
